#!/usr/bin/env python3
"""Generates large, realistic-looking SwiftKit sources (deterministic), so the binary vs source
comparison runs on a module with many classes, methods and long parameter lists."""
import random
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "Packages/SourcePkg/Sources/SwiftKit/Generated"
rng = random.Random(42)

VERBS = ["configure", "update", "apply", "schedule", "render", "normalize", "resample", "automate",
         "quantize", "crossfade", "route", "bounce", "arm", "freeze", "duplicate", "trim", "stretch",
         "transpose", "analyze", "meter"]
NOUNS = ["ChannelStrip", "AuxSend", "MasterBus", "TrackRegion", "TempoRamp", "LoopRange",
         "SidechainInput", "EffectSlot", "PunchWindow", "ClickTrack", "StemGroup", "Envelope",
         "FadeCurve", "VocalTake", "DrumPattern", "MidiClip"]
PARAMS = [
    ("channelIndex", "Int", "0"), ("trackIdentifier", "String", '""'),
    ("inputGainDecibels", "Double", "0"), ("outputGainDecibels", "Double", "0"),
    ("panPositionNormalized", "Double", "0"), ("isMutedDuringPlayback", "Bool", "false"),
    ("isSoloedExclusively", "Bool", "false"), ("auxSendLevelDecibels", "Double", "0"),
    ("sampleRateHertz", "Int", "48000"), ("bufferSizeFrames", "Int", "512"),
    ("startPositionBeats", "Double", "0"), ("endPositionBeats", "Double", "0"),
    ("crossfadeDurationMilliseconds", "Double", "0"), ("shouldPreserveFormants", "Bool", "true"),
    ("automationCurveTension", "Float", "0"), ("quantizeGridDivision", "Int", "16"),
    ("humanizeAmountPercent", "Double", "0"), ("targetLoudnessLUFS", "Double", "-14"),
    ("displayNameForUndoHistory", "String", '""'), ("isRecordArmedForInput", "Bool", "false"),
]


def method(name, count):
    params = rng.sample(PARAMS, count)
    sig = ",\n        ".join(f"{p}: {t}" for p, t, _ in params)
    body = " + ".join(f'"{p}=\\({p})"' for p, _, _ in params[:3])
    return (f"    /// {name} across {count} parameters.\n"
            f"    public func {name}(\n        {sig}\n    ) -> String {{\n"
            f"        {body}\n    }}\n")


def cls(name, methods, doc):
    names, out = set(), []
    while len(out) < methods:
        n = rng.choice(VERBS) + rng.choice(NOUNS)
        if n in names:
            n += f"Variant{len(out)}"
        names.add(n)
        out.append(method(n, rng.randint(5, 10)))
    return (f"/// {doc}\nopen class {name} {{\n    public init() {{}}\n\n" + "\n".join(out) + "}\n")


CLASSES = [
    ("SwiftKitMixerConsole", 100, "Large mixer facade: 100 methods with 5-10 labeled parameters each."),
    ("SwiftKitEffectRack", 12, "Effect chain management."),
    ("SwiftKitTransportBar", 12, "Transport and punch control."),
    ("SwiftKitWaveformRenderer", 12, "Waveform drawing parameters."),
    ("SwiftKitTempoMap", 12, "Tempo and time-signature map."),
]

OUT.mkdir(parents=True, exist_ok=True)
for name, n, doc in CLASSES:
    (OUT / f"{name}.swift").write_text("// Generated by Scripts/generate-large-sources.py. Do not edit.\n\n"
                                       + cls(name, n, doc))
print("\n".join(sorted(p.name for p in OUT.iterdir())))
